#ifndef KUGOU_API_H
#define KUGOU_API_H

typedef struct ProcessEnv {
  char *platform;
  char *KUGOU_API_GUID;
  char *KUGOU_API_DEV;
  char *KUGOU_API_MAC;
} ProcessEnv;
typedef struct JSContext JSContext;
JSContext *init(ProcessEnv *env);
int destroy();
JSContext *get_context();
int destroy_context(JSContext *ctx);

char *request(JSContext *ctx, const char *route, const char *cookies, const char *params, ProcessEnv *env);
char *yueku_fm(JSContext *ctx, const char *cookies, const char *params, ProcessEnv *env);
char *yueku_banner(JSContext *ctx, const char *cookies, const char *params, ProcessEnv *env);
char *yueku(JSContext *ctx, const char *cookies, const char *params, ProcessEnv *env);
char *youth_vip(JSContext *ctx, const char *cookies, const char *params, ProcessEnv *env);
char *youth_user_song(JSContext *ctx, const char *cookies, const char *params, ProcessEnv *env);
char *youth_union_vip(JSContext *ctx, const char *cookies, const char *params, ProcessEnv *env);
char *youth_month_vip_record(JSContext *ctx, const char *cookies, const char *params, ProcessEnv *env);
char *youth_listen_song(JSContext *ctx, const char *cookies, const char *params, ProcessEnv *env);
char *youth_dynamic_recent(JSContext *ctx, const char *cookies, const char *params, ProcessEnv *env);
char *youth_dynamic(JSContext *ctx, const char *cookies, const char *params, ProcessEnv *env);
char *youth_day_vip_upgrade(JSContext *ctx, const char *cookies, const char *params, ProcessEnv *env);
char *youth_day_vip(JSContext *ctx, const char *cookies, const char *params, ProcessEnv *env);
char *youth_channel_sub(JSContext *ctx, const char *cookies, const char *params, ProcessEnv *env);
char *youth_channel_song_detail(JSContext *ctx, const char *cookies, const char *params, ProcessEnv *env);
char *youth_channel_song(JSContext *ctx, const char *cookies, const char *params, ProcessEnv *env);
char *youth_channel_similar(JSContext *ctx, const char *cookies, const char *params, ProcessEnv *env);
char *youth_channel_detail(JSContext *ctx, const char *cookies, const char *params, ProcessEnv *env);
char *youth_channel_amway(JSContext *ctx, const char *cookies, const char *params, ProcessEnv *env);
char *youth_channel_all(JSContext *ctx, const char *cookies, const char *params, ProcessEnv *env);
char *video_url(JSContext *ctx, const char *cookies, const char *params, ProcessEnv *env);
char *video_privilege(JSContext *ctx, const char *cookies, const char *params, ProcessEnv *env);
char *video_detail(JSContext *ctx, const char *cookies, const char *params, ProcessEnv *env);
char *user_vip_detail(JSContext *ctx, const char *cookies, const char *params, ProcessEnv *env);
char *user_video_love(JSContext *ctx, const char *cookies, const char *params, ProcessEnv *env);
char *user_video_collect(JSContext *ctx, const char *cookies, const char *params, ProcessEnv *env);
char *user_playlist(JSContext *ctx, const char *cookies, const char *params, ProcessEnv *env);
char *user_listen(JSContext *ctx, const char *cookies, const char *params, ProcessEnv *env);
char *user_history(JSContext *ctx, const char *cookies, const char *params, ProcessEnv *env);
char *user_follow(JSContext *ctx, const char *cookies, const char *params, ProcessEnv *env);
char *user_detail(JSContext *ctx, const char *cookies, const char *params, ProcessEnv *env);
char *user_cloud_url(JSContext *ctx, const char *cookies, const char *params, ProcessEnv *env);
char *user_cloud(JSContext *ctx, const char *cookies, const char *params, ProcessEnv *env);
char *top_song(JSContext *ctx, const char *cookies, const char *params, ProcessEnv *env);
char *top_playlist(JSContext *ctx, const char *cookies, const char *params, ProcessEnv *env);
char *top_ip(JSContext *ctx, const char *cookies, const char *params, ProcessEnv *env);
char *top_card_youth(JSContext *ctx, const char *cookies, const char *params, ProcessEnv *env);
char *top_card(JSContext *ctx, const char *cookies, const char *params, ProcessEnv *env);
char *top_album(JSContext *ctx, const char *cookies, const char *params, ProcessEnv *env);
char *theme_playlist_track(JSContext *ctx, const char *cookies, const char *params, ProcessEnv *env);
char *theme_playlist(JSContext *ctx, const char *cookies, const char *params, ProcessEnv *env);
char *theme_music_detail(JSContext *ctx, const char *cookies, const char *params, ProcessEnv *env);
char *theme_music(JSContext *ctx, const char *cookies, const char *params, ProcessEnv *env);
char *song_url_new(JSContext *ctx, const char *cookies, const char *params, ProcessEnv *env);
char *song_url(JSContext *ctx, const char *cookies, const char *params, ProcessEnv *env);
char *song_ranking_filter(JSContext *ctx, const char *cookies, const char *params, ProcessEnv *env);
char *song_ranking(JSContext *ctx, const char *cookies, const char *params, ProcessEnv *env);
char *song_climax(JSContext *ctx, const char *cookies, const char *params, ProcessEnv *env);
char *singer_list(JSContext *ctx, const char *cookies, const char *params, ProcessEnv *env);
char *sheet_list(JSContext *ctx, const char *cookies, const char *params, ProcessEnv *env);
char *sheet_hot(JSContext *ctx, const char *cookies, const char *params, ProcessEnv *env);
char *sheet_detail(JSContext *ctx, const char *cookies, const char *params, ProcessEnv *env);
char *sheet_collection_detail(JSContext *ctx, const char *cookies, const char *params, ProcessEnv *env);
char *sheet_collection(JSContext *ctx, const char *cookies, const char *params, ProcessEnv *env);
char *server_now(JSContext *ctx, const char *cookies, const char *params, ProcessEnv *env);
char *search_suggest(JSContext *ctx, const char *cookies, const char *params, ProcessEnv *env);
char *search_mixed(JSContext *ctx, const char *cookies, const char *params, ProcessEnv *env);
char *search_lyric(JSContext *ctx, const char *cookies, const char *params, ProcessEnv *env);
char *search_hot(JSContext *ctx, const char *cookies, const char *params, ProcessEnv *env);
char *search_default(JSContext *ctx, const char *cookies, const char *params, ProcessEnv *env);
char *search_complex(JSContext *ctx, const char *cookies, const char *params, ProcessEnv *env);
char *search(JSContext *ctx, const char *cookies, const char *params, ProcessEnv *env);
char *scene_video_list(JSContext *ctx, const char *cookies, const char *params, ProcessEnv *env);
char *scene_music(JSContext *ctx, const char *cookies, const char *params, ProcessEnv *env);
char *scene_module_info(JSContext *ctx, const char *cookies, const char *params, ProcessEnv *env);
char *scene_module(JSContext *ctx, const char *cookies, const char *params, ProcessEnv *env);
char *scene_lists_v2(JSContext *ctx, const char *cookies, const char *params, ProcessEnv *env);
char *scene_lists(JSContext *ctx, const char *cookies, const char *params, ProcessEnv *env);
char *scene_collection_list(JSContext *ctx, const char *cookies, const char *params, ProcessEnv *env);
char *scene_audio_list(JSContext *ctx, const char *cookies, const char *params, ProcessEnv *env);
char *register_dev(JSContext *ctx, const char *cookies, const char *params, ProcessEnv *env);
char *recommend_songs(JSContext *ctx, const char *cookies, const char *params, ProcessEnv *env);
char *rank_vol(JSContext *ctx, const char *cookies, const char *params, ProcessEnv *env);
char *rank_top(JSContext *ctx, const char *cookies, const char *params, ProcessEnv *env);
char *rank_list(JSContext *ctx, const char *cookies, const char *params, ProcessEnv *env);
char *rank_info(JSContext *ctx, const char *cookies, const char *params, ProcessEnv *env);
char *rank_audio(JSContext *ctx, const char *cookies, const char *params, ProcessEnv *env);
char *privilege_lite(JSContext *ctx, const char *cookies, const char *params, ProcessEnv *env);
char *playlist_track_all_new(JSContext *ctx, const char *cookies, const char *params, ProcessEnv *env);
char *playlist_track_all(JSContext *ctx, const char *cookies, const char *params, ProcessEnv *env);
char *playlist_tracks_del(JSContext *ctx, const char *cookies, const char *params, ProcessEnv *env);
char *playlist_tracks_add(JSContext *ctx, const char *cookies, const char *params, ProcessEnv *env);
char *playlist_tags(JSContext *ctx, const char *cookies, const char *params, ProcessEnv *env);
char *playlist_similar(JSContext *ctx, const char *cookies, const char *params, ProcessEnv *env);
char *playlist_effect(JSContext *ctx, const char *cookies, const char *params, ProcessEnv *env);
char *playlist_detail(JSContext *ctx, const char *cookies, const char *params, ProcessEnv *env);
char *playlist_del(JSContext *ctx, const char *cookies, const char *params, ProcessEnv *env);
char *playlist_add(JSContext *ctx, const char *cookies, const char *params, ProcessEnv *env);
char *playhistory_upload(JSContext *ctx, const char *cookies, const char *params, ProcessEnv *env);
char *personal_fm(JSContext *ctx, const char *cookies, const char *params, ProcessEnv *env);
char *pc_diantai(JSContext *ctx, const char *cookies, const char *params, ProcessEnv *env);
char *lyric(JSContext *ctx, const char *cookies, const char *params, ProcessEnv *env);
char *longaudio_week_recommend(JSContext *ctx, const char *cookies, const char *params, ProcessEnv *env);
char *longaudio_vip_recommend(JSContext *ctx, const char *cookies, const char *params, ProcessEnv *env);
char *longaudio_rank_recommend(JSContext *ctx, const char *cookies, const char *params, ProcessEnv *env);
char *longaudio_daily_recommend(JSContext *ctx, const char *cookies, const char *params, ProcessEnv *env);
char *longaudio_album_detail(JSContext *ctx, const char *cookies, const char *params, ProcessEnv *env);
char *longaudio_album_audios(JSContext *ctx, const char *cookies, const char *params, ProcessEnv *env);
char *login_wx_create(JSContext *ctx, const char *cookies, const char *params, ProcessEnv *env);
char *login_wx_check(JSContext *ctx, const char *cookies, const char *params, ProcessEnv *env);
char *login_token(JSContext *ctx, const char *cookies, const char *params, ProcessEnv *env);
char *login_qr_key(JSContext *ctx, const char *cookies, const char *params, ProcessEnv *env);
char *login_qr_create(JSContext *ctx, const char *cookies, const char *params, ProcessEnv *env);
char *login_qr_check(JSContext *ctx, const char *cookies, const char *params, ProcessEnv *env);
char *login_openplat(JSContext *ctx, const char *cookies, const char *params, ProcessEnv *env);
char *login_device(JSContext *ctx, const char *cookies, const char *params, ProcessEnv *env);
char *login_cellphone(JSContext *ctx, const char *cookies, const char *params, ProcessEnv *env);
char *login(JSContext *ctx, const char *cookies, const char *params, ProcessEnv *env);
char *lastest_songs_listen(JSContext *ctx, const char *cookies, const char *params, ProcessEnv *env);
char *krm_audio(JSContext *ctx, const char *cookies, const char *params, ProcessEnv *env);
char *kmr_audio_mv(JSContext *ctx, const char *cookies, const char *params, ProcessEnv *env);
char *ip_zone_home(JSContext *ctx, const char *cookies, const char *params, ProcessEnv *env);
char *ip_zone(JSContext *ctx, const char *cookies, const char *params, ProcessEnv *env);
char *ip_playlist(JSContext *ctx, const char *cookies, const char *params, ProcessEnv *env);
char *ip_dateil(JSContext *ctx, const char *cookies, const char *params, ProcessEnv *env);
char *ip(JSContext *ctx, const char *cookies, const char *params, ProcessEnv *env);
char *images_audio(JSContext *ctx, const char *cookies, const char *params, ProcessEnv *env);
char *images(JSContext *ctx, const char *cookies, const char *params, ProcessEnv *env);
char *fm_songs(JSContext *ctx, const char *cookies, const char *params, ProcessEnv *env);
char *fm_recommend(JSContext *ctx, const char *cookies, const char *params, ProcessEnv *env);
char *fm_image(JSContext *ctx, const char *cookies, const char *params, ProcessEnv *env);
char *fm_class(JSContext *ctx, const char *cookies, const char *params, ProcessEnv *env);
char *favorite_count(JSContext *ctx, const char *cookies, const char *params, ProcessEnv *env);
char *everyday_style_recommend(JSContext *ctx, const char *cookies, const char *params, ProcessEnv *env);
char *everyday_recommend(JSContext *ctx, const char *cookies, const char *params, ProcessEnv *env);
char *everyday_history(JSContext *ctx, const char *cookies, const char *params, ProcessEnv *env);
char *everyday_friend(JSContext *ctx, const char *cookies, const char *params, ProcessEnv *env);
char *comment_playlist(JSContext *ctx, const char *cookies, const char *params, ProcessEnv *env);
char *comment_music_hotword(JSContext *ctx, const char *cookies, const char *params, ProcessEnv *env);
char *comment_music_classify(JSContext *ctx, const char *cookies, const char *params, ProcessEnv *env);
char *comment_music(JSContext *ctx, const char *cookies, const char *params, ProcessEnv *env);
char *comment_floor(JSContext *ctx, const char *cookies, const char *params, ProcessEnv *env);
char *comment_count(JSContext *ctx, const char *cookies, const char *params, ProcessEnv *env);
char *comment_album(JSContext *ctx, const char *cookies, const char *params, ProcessEnv *env);
char *captcha_sent(JSContext *ctx, const char *cookies, const char *params, ProcessEnv *env);
char *brush(JSContext *ctx, const char *cookies, const char *params, ProcessEnv *env);
char *audio_related(JSContext *ctx, const char *cookies, const char *params, ProcessEnv *env);
char *audio_ktv_total(JSContext *ctx, const char *cookies, const char *params, ProcessEnv *env);
char *audio_accompany_matching(JSContext *ctx, const char *cookies, const char *params, ProcessEnv *env);
char *audio(JSContext *ctx, const char *cookies, const char *params, ProcessEnv *env);
char *artist_videos(JSContext *ctx, const char *cookies, const char *params, ProcessEnv *env);
char *artist_unfollow(JSContext *ctx, const char *cookies, const char *params, ProcessEnv *env);
char *artist_lists(JSContext *ctx, const char *cookies, const char *params, ProcessEnv *env);
char *artist_honour(JSContext *ctx, const char *cookies, const char *params, ProcessEnv *env);
char *artist_follow_newsongs(JSContext *ctx, const char *cookies, const char *params, ProcessEnv *env);
char *artist_follow(JSContext *ctx, const char *cookies, const char *params, ProcessEnv *env);
char *artist_detail(JSContext *ctx, const char *cookies, const char *params, ProcessEnv *env);
char *artist_audios(JSContext *ctx, const char *cookies, const char *params, ProcessEnv *env);
char *artist_albums(JSContext *ctx, const char *cookies, const char *params, ProcessEnv *env);
char *album_songs(JSContext *ctx, const char *cookies, const char *params, ProcessEnv *env);
char *album_shop(JSContext *ctx, const char *cookies, const char *params, ProcessEnv *env);
char *album_detail(JSContext *ctx, const char *cookies, const char *params, ProcessEnv *env);
char *album(JSContext *ctx, const char *cookies, const char *params, ProcessEnv *env);
char *ai_recommend(JSContext *ctx, const char *cookies, const char *params, ProcessEnv *env);

#endif