name: macOS Build

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  build:
    timeout-minutes: 30
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        include:
          - os: macos-14
            architecture: x64
            preset: macos-x64-clang
          - os: macos-14
            architecture: arm64
            preset: macos-arm64-clang

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          architecture: ${{ matrix.architecture }}
          cache: "pnpm"

      - name: Install system dependencies
        run: |
          brew update
          brew install \
            cmake \
            pkg-config \
            curl

      - name: Pull NCM project submodule
        run: node scripts/pull_ncm.js

      - name: Install dependencies
        run: pnpm install

      - name: Build JavaScript bundle
        run: npx webpack

      - name: Configure CMake
        run: cmake --preset ${{ matrix.preset }}

      - name: Build qjsc target
        run: cmake --build --preset ${{ matrix.preset }}-Release --target qjsc

      - name: Build main target
        run: cmake --build --preset ${{ matrix.preset }}-Release -j$(sysctl -n hw.ncpu)

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: macos-${{ matrix.architecture }}-release
          path: |
            build/macos/${{ matrix.architecture }}/${{ matrix.preset }}/Release/lib/**
            build/macos/${{ matrix.architecture }}/${{ matrix.preset }}/Release/include/*
